/* Sprint 60 F05: deterministic optimizer equivalence probe generator.
 *
 * Each generated translation unit is strict, header-free C17.  It computes
 * a small, generator-modelled checksum, checks that result against a baked
 * constant, and prints a stable success line.  The five template families
 * deliberately exercise different optimizer regions without reproducing the
 * descending-loop fusion or call-heavy exact-trip unroll cases already held
 * by the audit regression corpus.
 *
 *     optgen --out DIR --count N [--seed N] [--hash]
 *
 * The optional hash is FNV-1a over every output filename and source byte in
 * generation order.  It is a sequence fingerprint, not a security primitive.
 */

#include <errno.h>
#include <limits.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

#define SOURCE_CAP 16384
#define PATH_CAP 4096
#define MAX_CASES 1000000ull

typedef struct {
    char data[SOURCE_CAP];
    size_t len;
} Source;

static unsigned long long rng_state;

static unsigned long long rnd(void)
{
    unsigned long long z;

    rng_state += 0x9E3779B97F4A7C15ull;
    z = rng_state;
    z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ull;
    z = (z ^ (z >> 27)) * 0x94D049BB133111EBull;
    return z ^ (z >> 31);
}

static unsigned pick(unsigned n)
{
    return (unsigned)(rnd() % (unsigned long long)n);
}

static void source_add(Source *s, const char *text)
{
    size_t n = strlen(text);

    if (n > sizeof(s->data) - s->len - 1) {
        fprintf(stderr, "optgen: generated source exceeds %u bytes\n",
                (unsigned)sizeof(s->data));
        exit(2);
    }
    memcpy(s->data + s->len, text, n);
    s->len += n;
    s->data[s->len] = '\0';
}

static void source_printf(Source *s, const char *fmt, ...)
{
    va_list ap;
    int n;

    va_start(ap, fmt);
    n = vsnprintf(s->data + s->len, sizeof(s->data) - s->len, fmt, ap);
    va_end(ap);
    if (n < 0 || (size_t)n >= sizeof(s->data) - s->len) {
        fprintf(stderr, "optgen: generated source exceeds %u bytes\n",
                (unsigned)sizeof(s->data));
        exit(2);
    }
    s->len += (size_t)n;
}

static void emit_header(Source *s, unsigned long long case_no, unsigned family)
{
    source_printf(s,
                  "// OPT_EQ: all\n"
                  "/* generated by optgen: case %06llu, family %u */\n"
                  "extern int puts(const char *);\n\n",
                  case_no, family);
}

static void emit_footer(Source *s, unsigned long long case_no,
                        unsigned long expected)
{
    source_printf(s,
                  "    if (got != %luUL)\n"
                  "        return 1;\n"
                  "    puts(\"case-%06llu:%lu\");\n"
                  "    return 0;\n"
                  "}\n",
                  expected, case_no, expected);
}

static void emit_scalar_branch(Source *s, unsigned long long case_no)
{
    unsigned long a = 3UL + pick(29);
    unsigned long b = 5UL + pick(31);
    unsigned long c = 7UL + pick(23);
    unsigned long expected;

    expected = a * 7UL + b * 3UL + c;
    if (((a ^ b) & 1UL) != 0)
        expected += a + c;
    else
        expected += b + c * 2UL;
    if (a < b)
        expected ^= a * 5UL;
    else
        expected ^= b * 5UL;

    emit_header(s, case_no, 0);
    source_printf(s,
                  "int main(void)\n"
                  "{\n"
                  "    unsigned long a = %luUL;\n"
                  "    unsigned long b = %luUL;\n"
                  "    unsigned long c = %luUL;\n"
                  "    unsigned long got = a * 7UL + b * 3UL + c;\n\n"
                  "    if (((a ^ b) & 1UL) != 0)\n"
                  "        got += a + c;\n"
                  "    else\n"
                  "        got += b + c * 2UL;\n"
                  "    if (a < b)\n"
                  "        got ^= a * 5UL;\n"
                  "    else\n"
                  "        got ^= b * 5UL;\n",
                  a, b, c);
    emit_footer(s, case_no, expected);
}

static void emit_call_chain(Source *s, unsigned long long case_no)
{
    unsigned long x = 2UL + pick(25);
    unsigned long m = 2UL + pick(7);
    unsigned long k = 1UL + pick(13);
    unsigned long expected = ((x * m + k) ^ (x + k)) + m * 11UL;

    emit_header(s, case_no, 1);
    source_printf(s,
                  "static unsigned long affine(unsigned long x)\n"
                  "{\n"
                  "    return x * %luUL + %luUL;\n"
                  "}\n\n"
                  "static unsigned long combine(unsigned long x)\n"
                  "{\n"
                  "    return (affine(x) ^ (x + %luUL)) + %luUL;\n"
                  "}\n\n"
                  "int main(void)\n"
                  "{\n"
                  "    unsigned long got = combine(%luUL);\n",
                  m, k, k, m * 11UL, x);
    emit_footer(s, case_no, expected);
}

static void emit_map_reduce(Source *s, unsigned long long case_no)
{
    unsigned long mul = 2UL + pick(5);
    unsigned long add = 1UL + pick(17);
    unsigned long values[16];
    unsigned long expected = 0;
    unsigned i;

    for (i = 0; i < 16; i++) {
        values[i] = (unsigned long)(i + 1U) * (1UL + pick(4));
        expected += values[i] * mul + add;
    }

    emit_header(s, case_no, 2);
    source_add(s, "int main(void)\n"
                  "{\n"
                  "    unsigned long in[16] = {");
    for (i = 0; i < 16; i++)
        source_printf(s, "%s%luUL", i == 0 ? "" : ", ", values[i]);
    source_printf(s,
                  "};\n"
                  "    unsigned long out[16];\n"
                  "    unsigned long got = 0;\n"
                  "    unsigned i;\n\n"
                  "    for (i = 0; i < 16; i++)\n"
                  "        out[i] = in[i] * %luUL + %luUL;\n"
                  "    for (i = 0; i < 16; i++)\n"
                  "        got += out[i];\n",
                  mul, add);
    emit_footer(s, case_no, expected);
}

static void emit_nested_invariant(Source *s, unsigned long long case_no)
{
    unsigned long bias = 1UL + pick(11);
    unsigned long scale = 1UL + pick(5);
    unsigned long expected = 0;
    unsigned i, j;

    for (i = 0; i < 4; i++)
        for (j = 0; j < 6; j++)
            expected += (unsigned long)(i * 6U + j + 1U) * scale + bias * 3UL;

    emit_header(s, case_no, 3);
    source_printf(
        s,
        "int main(void)\n"
        "{\n"
        "    unsigned long got = 0;\n"
        "    unsigned long invariant = %luUL * 3UL;\n"
        "    unsigned i;\n"
        "    unsigned j;\n\n"
        "    for (i = 0; i < 4; i++) {\n"
        "        for (j = 0; j < 6; j++)\n"
        "            got += (i * 6UL + j + 1UL) * %luUL + invariant;\n"
        "    }\n",
        bias, scale);
    emit_footer(s, case_no, expected);
}

static void emit_adjacent_independent(Source *s, unsigned long long case_no)
{
    unsigned long a_bias = 1UL + pick(9);
    unsigned long b_bias = 2UL + pick(11);
    unsigned long expected = 0;
    unsigned i;

    for (i = 0; i < 20; i++)
        expected += (unsigned long)i * 2UL + a_bias;
    for (i = 0; i < 20; i++)
        expected ^= (unsigned long)i * 3UL + b_bias;

    emit_header(s, case_no, 4);
    source_printf(s,
                  "int main(void)\n"
                  "{\n"
                  "    unsigned long a[20];\n"
                  "    unsigned long b[20];\n"
                  "    unsigned long got = 0;\n"
                  "    unsigned i;\n\n"
                  "    for (i = 0; i < 20; i++)\n"
                  "        a[i] = i * 2UL + %luUL;\n"
                  "    for (i = 0; i < 20; i++)\n"
                  "        b[i] = i * 3UL + %luUL;\n"
                  "    for (i = 0; i < 20; i++)\n"
                  "        got += a[i];\n"
                  "    for (i = 0; i < 20; i++)\n"
                  "        got ^= b[i];\n",
                  a_bias, b_bias);
    emit_footer(s, case_no, expected);
}

static void generate(Source *s, unsigned long long case_no, unsigned family)
{
    memset(s, 0, sizeof(*s));
    switch (family) {
    case 0:
        emit_scalar_branch(s, case_no);
        break;
    case 1:
        emit_call_chain(s, case_no);
        break;
    case 2:
        emit_map_reduce(s, case_no);
        break;
    case 3:
        emit_nested_invariant(s, case_no);
        break;
    default:
        emit_adjacent_independent(s, case_no);
        break;
    }
}

static unsigned long long hash_bytes(unsigned long long h, const char *p,
                                     size_t n)
{
    size_t i;

    for (i = 0; i < n; i++) {
        h ^= (unsigned char)p[i];
        h *= 1099511628211ull;
    }
    return h;
}

static int parse_u64(const char *arg, const char *name,
                     unsigned long long *value)
{
    char *end;
    unsigned long long parsed;

    if (arg[0] == '\0' || arg[0] == '-') {
        fprintf(stderr, "optgen: invalid %s '%s'\n", name, arg);
        return 0;
    }
    errno = 0;
    end = NULL;
    parsed = strtoull(arg, &end, 10);
    if (errno == ERANGE || end == arg || *end != '\0') {
        fprintf(stderr, "optgen: invalid %s '%s'\n", name, arg);
        return 0;
    }
    *value = parsed;
    return 1;
}

static int ensure_outdir(const char *path)
{
    struct stat st;

    if (mkdir(path, 0777) == 0)
        return 1;
    if (errno != EEXIST) {
        fprintf(stderr, "optgen: cannot create '%s': %s\n", path,
                strerror(errno));
        return 0;
    }
    if (stat(path, &st) != 0 || !S_ISDIR(st.st_mode)) {
        fprintf(stderr, "optgen: output path '%s' is not a directory\n", path);
        return 0;
    }
    return 1;
}

static void usage(void)
{
    fprintf(stderr, "usage: optgen --out DIR --count N [--seed N] [--hash]\n");
}

int main(int argc, char **argv)
{
    const char *outdir = NULL;
    unsigned long long count = ULLONG_MAX;
    unsigned long long seed = 1;
    unsigned long long digest = 14695981039346656037ull;
    int print_hash = 0;
    int i;
    unsigned long long case_no;

    for (i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--out") == 0 && i + 1 < argc) {
            outdir = argv[++i];
        } else if (strcmp(argv[i], "--count") == 0 && i + 1 < argc) {
            if (!parse_u64(argv[++i], "count", &count))
                return 2;
        } else if (strcmp(argv[i], "--seed") == 0 && i + 1 < argc) {
            if (!parse_u64(argv[++i], "seed", &seed))
                return 2;
        } else if (strcmp(argv[i], "--hash") == 0) {
            print_hash = 1;
        } else {
            usage();
            return 2;
        }
    }
    if (outdir == NULL || count == ULLONG_MAX || count > MAX_CASES) {
        if (count > MAX_CASES && count != ULLONG_MAX)
            fprintf(stderr, "optgen: count must be at most %llu\n", MAX_CASES);
        else
            usage();
        return 2;
    }
    if (!ensure_outdir(outdir))
        return 2;

    rng_state = seed;
    for (case_no = 0; case_no < count; case_no++) {
        Source source;
        char name[32];
        char path[PATH_CAP];
        FILE *out;
        int n;

        n = snprintf(name, sizeof(name), "case-%06llu.c", case_no);
        if (n < 0 || (size_t)n >= sizeof(name)) {
            fprintf(stderr, "optgen: case filename overflow\n");
            return 2;
        }
        n = snprintf(path, sizeof(path), "%s/%s", outdir, name);
        if (n < 0 || (size_t)n >= sizeof(path)) {
            fprintf(stderr, "optgen: output path is too long\n");
            return 2;
        }
        generate(&source, case_no, (unsigned)(case_no % 5ull));
        out = fopen(path, "wb");
        if (out == NULL) {
            fprintf(stderr, "optgen: cannot open '%s': %s\n", path,
                    strerror(errno));
            return 2;
        }
        if (fwrite(source.data, 1, source.len, out) != source.len) {
            fprintf(stderr, "optgen: cannot write '%s'\n", path);
            fclose(out);
            return 2;
        }
        if (fclose(out) != 0) {
            fprintf(stderr, "optgen: cannot close '%s': %s\n", path,
                    strerror(errno));
            return 2;
        }
        digest = hash_bytes(digest, name, strlen(name));
        digest = hash_bytes(digest, "\0", 1);
        digest = hash_bytes(digest, source.data, source.len);
    }
    if (print_hash)
        printf("optgen hash %016llx\n", digest);
    return 0;
}
