// GENERATED by scripts/gen_format_matrix.sh; edit matrix.tsv.
// FLAGS: -fsyntax-only -Wformat
// WARN_COUNT: 1
int scanf(const char *, ...);
void test(void)
{
    signed char sc; unsigned char uc; short sh; unsigned short ush;
    int i; unsigned int ui; long l; unsigned long ul;
    long long ll; unsigned long long ull;
    float f; double d; long double ld; char cbuf[4]; int wbuf[4];
    void *vp;
    // WARN_CHECK: format expects argument of type 'int *'
    scanf("%n", l);
}
