#!/bin/sh
# Generates the unit-test registry (strict C11: no constructor attributes).
# Usage: gen_unit_registry.sh <output.c> <test_*.c>...
# Scans for `^void test_<name>(TestCtx *` at line starts. Files must be
# passed in sorted order (the Makefile sorts) and grep preserves in-file
# line order, so the registry — and therefore test order and failure
# output — is deterministic.
set -eu
LC_ALL=C
export LC_ALL

out=$1
shift

tmp=${out}.tmp
{
    echo "/* Generated by scripts/gen_unit_registry.sh - do not edit. */"
    echo "#include \"unit.h\""
    echo ""
    for f in "$@"; do
        sed -n 's/^void \(test_[a-z0-9_]*\)(TestCtx \*.*/void \1(TestCtx *);/p' "$f"
    done
    echo ""
    echo "const UnitTest cgf_unit_tests[] = {"
    for f in "$@"; do
        sed -n 's/^void \(test_[a-z0-9_]*\)(TestCtx \*.*/    { "\1", \1 },/p' "$f"
    done
    echo "};"
    echo "const size_t cgf_unit_test_count ="
    echo "    sizeof(cgf_unit_tests) / sizeof(cgf_unit_tests[0]);"
} >"$tmp"
mv "$tmp" "$out"
