#!/bin/sh
# Generate the committed Sprint 39 fire/nofire matrix from one canonical
# semantic manifest.  Output is stable under dash and independent of locale.
set -eu
LC_ALL=C
export LC_ALL

manifest=${1:-tests/warn/format/matrix.tsv}
out=${2:-tests/warn/format/matrix}

mkdir -p "$out/printf" "$out/scanf"

while read -r family key format good bad expected extra; do
    case "$family" in
    \#*|'') continue ;;
    printf) prototype='int printf(const char *, ...);' ;;
    scanf) prototype='int scanf(const char *, ...);' ;;
    *) echo "gen_format_matrix: unknown family: $family" >&2; exit 1 ;;
    esac
    [ -z "${extra:-}" ] && [ -n "${expected:-}" ] || {
        echo "gen_format_matrix: malformed row: $family $key" >&2
        exit 1
    }
    case "$key" in
    *[!a-z0-9_]*|'')
        echo "gen_format_matrix: unsafe key: $key" >&2
        exit 1
        ;;
    esac
    case "$expected" in
    int) expected_text='int' ;;
    long) expected_text='long' ;;
    long_long) expected_text='long long' ;;
    intmax_t) expected_text='intmax_t' ;;
    ssize_t) expected_text='ssize_t' ;;
    ptrdiff_t) expected_text='ptrdiff_t' ;;
    unsigned_int) expected_text='unsigned int' ;;
    unsigned_long) expected_text='unsigned long' ;;
    unsigned_long_long) expected_text='unsigned long long' ;;
    uintmax_t) expected_text='uintmax_t' ;;
    size_t) expected_text='size_t' ;;
    double) expected_text='double' ;;
    long_double) expected_text='long double' ;;
    wint_t) expected_text='wint_t' ;;
    char_ptr) expected_text='char *' ;;
    wchar_ptr) expected_text='wchar_t *' ;;
    void_ptr) expected_text='void *' ;;
    int_ptr) expected_text='int *' ;;
    signed_char_ptr) expected_text='signed char *' ;;
    short_ptr) expected_text='short *' ;;
    long_ptr) expected_text='long *' ;;
    long_long_ptr) expected_text='long long *' ;;
    intmax_ptr) expected_text='intmax_t *' ;;
    ssize_ptr) expected_text='ssize_t *' ;;
    ptrdiff_ptr) expected_text='ptrdiff_t *' ;;
    unsigned_int_ptr) expected_text='unsigned int *' ;;
    unsigned_char_ptr) expected_text='unsigned char *' ;;
    unsigned_short_ptr) expected_text='unsigned short *' ;;
    unsigned_long_ptr) expected_text='unsigned long *' ;;
    unsigned_long_long_ptr) expected_text='unsigned long long *' ;;
    uintmax_ptr) expected_text='uintmax_t *' ;;
    size_ptr) expected_text='size_t *' ;;
    float_ptr) expected_text='float *' ;;
    double_ptr) expected_text='double *' ;;
    long_double_ptr) expected_text='long double *' ;;
    void_ptr_ptr) expected_text='void **' ;;
    *)
        echo "gen_format_matrix: unknown expected type: $expected" >&2
        exit 1
        ;;
    esac

    fire="$out/$family/${key}_fire.c"
    nofire="$out/$family/${key}_nofire.c"
    {
        printf '%s\n' '// GENERATED by scripts/gen_format_matrix.sh; edit matrix.tsv.'
        printf '%s\n' '// FLAGS: -fsyntax-only -Wformat'
        printf '%s\n' '// WARN_COUNT: 1' "$prototype" 'void test(void)' '{'
        printf '%s\n' '    signed char sc; unsigned char uc; short sh; unsigned short ush;'
        printf '%s\n' '    int i; unsigned int ui; long l; unsigned long ul;'
        printf '%s\n' '    long long ll; unsigned long long ull;'
        printf '%s\n' '    float f; double d; long double ld; char cbuf[4]; int wbuf[4];'
        printf '%s\n' '    void *vp;'
        printf '    // WARN_CHECK: format expects argument of type '\''%s'\''\n' "$expected_text"
        printf '    %s("%s", %s);\n' "$family" "$format" "$bad"
        printf '%s\n' '}'
    } > "$fire"
    {
        printf '%s\n' '// GENERATED by scripts/gen_format_matrix.sh; edit matrix.tsv.'
        printf '%s\n' '// FLAGS: -fsyntax-only -Wformat'
        printf '%s\n' '// WARN_COUNT: 0' "$prototype" 'void test(void)' '{'
        printf '%s\n' '    signed char sc; unsigned char uc; short sh; unsigned short ush;'
        printf '%s\n' '    int i; unsigned int ui; long l; unsigned long ul;'
        printf '%s\n' '    long long ll; unsigned long long ull;'
        printf '%s\n' '    float f; double d; long double ld; char cbuf[4]; int wbuf[4];'
        printf '%s\n' '    void *vp;'
        printf '    %s("%s", %s);\n' "$family" "$format" "$good"
        printf '%s\n' '}'
    } > "$nofire"
done < "$manifest"
